-- [[ KIKO Nametag System v2 ]]
-- Generated by KIKO Discord Bot

-- =============================================
-- GRADIENT CONFIGURATION  ← edit these!
-- =============================================
local GRADIENT_COLOR_A    = Color3.fromRGB(255, 255, 255)   -- default colour 1 (normal users)
local GRADIENT_COLOR_B    = Color3.fromRGB(0, 0, 0)   -- default colour 2 (normal users)
local GRADIENT_SPIN_SPEED = 60   -- degrees/sec the gradient rotates

-- =============================================
-- ZOOM-OUT SQUARE CONFIGURATION  ← edit these!
-- =============================================
local ZOOMOUT_SIZE     = UDim2.new(0, 44, 0, 44)
local ZOOMOUT_RADIUS   = UDim.new(0, 8)
local ZOOMOUT_DISTANCE = 100

-- =============================================

local plrs       = game:GetService("Players")
local txtChat    = game:GetService("TextChatService")
local tweenSvc   = game:GetService("TweenService")
local runSvc     = game:GetService("RunService")
local starterGui = game:GetService("StarterGui")
local lp         = plrs.LocalPlayer

local taggedPlrs    = {}
local respondedPlrs = {}
local mutualPlrs    = {}

local defaultTagSz  = UDim2.new(0, 230, 0, 42)
local tagOff        = Vector3.new(0, 2.2, 0)
local LOGO_ASSET_ID = "rbxassetid://"

local customPlayers = {
	["ykzott"] = {
		color      = Color3.fromRGB(0, 0, 0),
		glowColor  = Color3.fromRGB(255, 255, 255),
		customName = "Management",
	},
	["123rubi2lo"] = {
		color      = Color3.fromRGB(0, 0, 0),
		glowColor  = Color3.fromRGB(255, 255, 255),
		customName = "Management",
	},
	["kenzotwo09"] = {
		color      = Color3.fromRGB(0, 0, 0),
		glowColor  = Color3.fromRGB(255, 255, 255),
		customName = "Management",
	},
	["MRM0121"] = {
		color      = Color3.fromRGB(0, 0, 0),
		glowColor  = Color3.fromRGB(255, 255, 255),
		customName = "Management",
	},
	["gsrhgrhehdrh"] = {
		color      = Color3.fromRGB(255, 192, 203),
		glowColor  = Color3.fromRGB(255, 255, 255),
		customName = "MARLON",
	},
	["Adamalchoum2"] = {
		color      = Color3.fromRGB(128, 0, 128),
		glowColor  = Color3.fromRGB(0, 0, 0),
		customName = "KNOBHEAD",
	},
	["ethanbhe_4"] = {
		color      = Color3.fromRGB(255, 255, 255),
		glowColor  = Color3.fromRGB(255, 255, 255),
		customName = "KIKO BOOSTER",
		gradientA  = Color3.fromRGB(255, 105, 180),
		gradientB  = Color3.fromRGB(0, 0, 0),
	},
	["Robloxianw3s1j0e2o"] = {
		color      = Color3.fromRGB(255, 255, 255),
		glowColor  = Color3.fromRGB(255, 255, 255),
		customName = "OWNER",
		gradientA  = Color3.fromRGB(255, 229, 0),
		gradientB  = Color3.fromRGB(26, 26, 26),
	},
	["6vryzx"] = {
		color      = Color3.fromRGB(0, 0, 0),
		glowColor  = Color3.fromRGB(255, 255, 255),
		customName = "EX CO-OWNER",
		gradientA  = Color3.fromRGB(0, 0, 225),
		gradientB  = Color3.fromRGB(0, 0, 0),
	},
}

starterGui:SetCore("SendNotification", {
	Title    = "Nametag System";
	Text     = "Help From Absent";
	Duration = 5;
})

local function getCustomData(plr)
	if customPlayers[plr.Name]   then return customPlayers[plr.Name]   end
	if customPlayers[plr.UserId] then return customPlayers[plr.UserId] end
	return nil
end

local function getAvatarImage(plr)
	local ok, url = pcall(function()
		return plrs:GetUserThumbnailAsync(plr.UserId, Enum.ThumbnailType.HeadShot, Enum.ThumbnailSize.Size100x100)
	end)
	if ok then return url end
	return LOGO_ASSET_ID
end

local GLITCH_CHARS = {"#","@","!","$","%","&","?","*","/","\\","|","~","^","X","Z"}

local function glitchString(original)
	local result = {}
	for i = 1, #original do
		if math.random() < 0.4 then
			result[i] = GLITCH_CHARS[math.random(1, #GLITCH_CHARS)]
		else
			result[i] = string.sub(original, i, i)
		end
	end
	return table.concat(result)
end

local function buildTag(plr)
	if not mutualPlrs[plr.UserId] then return end
	if taggedPlrs[plr.UserId]     then return end
	local char = plr.Character
	if not char then return end
	local hd  = char:FindFirstChild("Head")
	if not hd  then return end
	local hrp = char:FindFirstChild("HumanoidRootPart")
	if not hrp then return end

	taggedPlrs[plr.UserId] = true

	local pg = lp:WaitForChild("PlayerGui")
	for _, obj in pairs(pg:GetChildren()) do
		if obj.Name == "KZKNametag_" .. plr.UserId then obj:Destroy() end
	end

	local customData  = getCustomData(plr)
	local tagColor    = customData and customData.color    or Color3.fromRGB(255, 255, 255)
	local glowColor   = customData and customData.glowColor or Color3.fromRGB(255, 255, 255)
	local displayName = customData and customData.customName or "KIKO USER"
	local isOwner     = (displayName == "OWNER")
	local gradA = (customData and customData.gradientA) or GRADIENT_COLOR_A
	local gradB = (customData and customData.gradientB) or GRADIENT_COLOR_B
	local circleImage = getAvatarImage(plr)

	-- BillboardGui
	local bb = Instance.new("BillboardGui")
	bb.Name        = "KZKNametag_" .. plr.UserId
	bb.Parent      = pg
	bb.Size        = defaultTagSz
	bb.StudsOffset = tagOff
	bb.AlwaysOnTop = true
	bb.MaxDistance = math.huge
	bb.Adornee     = hd
	bb.Active      = true

	-- Click to teleport
	local btn = Instance.new("TextButton")
	btn.Parent               = bb
	btn.Size                 = UDim2.new(1, 0, 1, 0)
	btn.BackgroundTransparency = 1
	btn.Text                 = ""
	btn.ZIndex               = 20
	btn.AutoButtonColor      = false
	btn.Active               = true
	if plr ~= lp then
		btn.MouseButton1Click:Connect(function()
			local myChar = lp.Character
			if myChar and myChar:FindFirstChild("HumanoidRootPart") and hrp and hrp.Parent then
				myChar.HumanoidRootPart.CFrame = hrp.CFrame * CFrame.new(0, 0, 3)
			end
		end)
	end

	-- Main background frame
	local bg = Instance.new("Frame")
	bg.Parent               = bb
	bg.Size                 = UDim2.new(1, 0, 1, 0)
	bg.BackgroundColor3     = gradA
	bg.BorderSizePixel      = 0
	bg.BackgroundTransparency = 0.15
	bg.ZIndex               = 1

	local cr = Instance.new("UICorner")
	cr.CornerRadius = UDim.new(1, 0)
	cr.Parent       = bg

	local stroke = Instance.new("UIStroke")
	stroke.Parent          = bg
	stroke.Color           = Color3.fromRGB(255, 255, 255)
	stroke.Thickness       = 3
	stroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border

	-- Spinning gradient
	local grad = Instance.new("UIGradient")
	grad.Color    = ColorSequence.new(gradA, gradB)
	grad.Rotation = 0
	grad.Parent   = bg

	spawn(function()
		local rot = 0
		local last = tick()
		while bb and bb.Parent do
			local now = tick()
			rot = (rot + GRADIENT_SPIN_SPEED * (now - last)) % 360
			last = now
			grad.Rotation = rot
			grad.Color = ColorSequence.new(gradA, gradB)
			wait(1 / 30)
		end
	end)

	-- Glow frame
	local glow = Instance.new("Frame")
	glow.Name                 = "Glow"
	glow.Parent               = bg
	glow.Size                 = UDim2.new(1.1, 0, 1.1, 0)
	glow.Position             = UDim2.new(-0.05, 0, -0.05, 0)
	glow.BackgroundColor3     = glowColor
	glow.BackgroundTransparency = 1
	glow.BorderSizePixel      = 0
	glow.ZIndex               = 0
	local glowCr = Instance.new("UICorner")
	glowCr.CornerRadius = UDim.new(0, 13)
	glowCr.Parent       = glow

	-- Left image frame
	local IMG_W       = 38
	local IMG_PAD     = 10
	local TEXT_OFFSET = IMG_PAD + IMG_W + 6

	local avatarHolder = Instance.new("Frame")
	avatarHolder.Name               = "AvatarHolder"
	avatarHolder.Parent             = bg
	avatarHolder.Size               = UDim2.new(0, IMG_W, 1, -8)
	avatarHolder.Position           = UDim2.new(0, IMG_PAD, 0, 4)
	avatarHolder.BackgroundColor3   = gradA
	avatarHolder.BackgroundTransparency = 0.3
	avatarHolder.BorderSizePixel    = 0
	avatarHolder.ZIndex             = 4
	avatarHolder.ClipsDescendants   = true
	avatarHolder.Visible            = true

	local avatarCorner = Instance.new("UICorner")
	avatarCorner.CornerRadius = UDim.new(0, 6)
	avatarCorner.Parent       = avatarHolder

	-- Matching spinning gradient on the image frame
	local frameGrad = Instance.new("UIGradient")
	frameGrad.Color    = ColorSequence.new(gradA, gradB)
	frameGrad.Rotation = 0
	frameGrad.Parent   = avatarHolder

	spawn(function()
		local rot = 0
		local last = tick()
		while avatarHolder and avatarHolder.Parent do
			local now = tick()
			rot = (rot + GRADIENT_SPIN_SPEED * (now - last)) % 360
			last = now
			frameGrad.Rotation = rot
			frameGrad.Color = ColorSequence.new(gradA, gradB)
			wait(1 / 30)
		end
	end)

	local avatarStroke = Instance.new("UIStroke")
	avatarStroke.Parent          = avatarHolder
	avatarStroke.Color           = Color3.fromRGB(255, 255, 255)
	avatarStroke.Thickness       = 1
	avatarStroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
	avatarStroke.Transparency    = 0.5

	local avatarImg = Instance.new("ImageLabel")
	avatarImg.Name                 = "AvatarImage"
	avatarImg.Parent               = avatarHolder
	avatarImg.Size                 = UDim2.new(1, 0, 1, 0)
	avatarImg.BackgroundTransparency = 1
	avatarImg.Image                = circleImage
	avatarImg.ScaleType            = Enum.ScaleType.Crop
	avatarImg.ZIndex               = 5
	avatarImg.ImageTransparency    = 0.05

	local imgOverlay = Instance.new("Frame")
	imgOverlay.Parent               = avatarHolder
	imgOverlay.Size                 = UDim2.new(1, 0, 1, 0)
	imgOverlay.BackgroundColor3     = Color3.fromRGB(0, 0, 0)
	imgOverlay.BackgroundTransparency = 0.7
	imgOverlay.BorderSizePixel      = 0
	imgOverlay.ZIndex               = 6
	local imgOverlayCr = Instance.new("UICorner")
	imgOverlayCr.CornerRadius = UDim.new(0, 6)
	imgOverlayCr.Parent       = imgOverlay

	-- Display name label
	local txtBox = Instance.new("Frame")
	txtBox.Parent               = bg
	txtBox.Size                 = UDim2.new(1, -(TEXT_OFFSET + 5), 0.5, 0)
	txtBox.Position             = UDim2.new(0, TEXT_OFFSET, 0, 3)
	txtBox.BackgroundTransparency = 1
	txtBox.ZIndex               = 2

	local kzk = Instance.new("TextLabel")
	kzk.Name                 = "Left"
	kzk.Parent               = txtBox
	kzk.Size                 = UDim2.new(1, 0, 1, 0)
	kzk.BackgroundTransparency = 1
	kzk.Text                 = displayName
	kzk.TextColor3           = tagColor
	kzk.TextScaled           = true
	kzk.TextXAlignment       = Enum.TextXAlignment.Center
	kzk.Font                 = Enum.Font.GothamBold
	kzk.TextStrokeTransparency = 0.5
	kzk.ZIndex               = 3

	local kzkConstraint = Instance.new("UITextSizeConstraint")
	kzkConstraint.MaxTextSize = 16
	kzkConstraint.Parent      = kzk

	local kzkPadding = Instance.new("UIPadding")
	kzkPadding.PaddingLeft   = UDim.new(0, 2)
	kzkPadding.PaddingRight  = UDim.new(0, 2)
	kzkPadding.PaddingTop    = UDim.new(0, 1)
	kzkPadding.PaddingBottom = UDim.new(0, 1)
	kzkPadding.Parent        = kzk

	local usr = Instance.new("TextLabel")
	usr.Parent               = bg
	usr.Size                 = UDim2.new(0, 0, 0, 0)
	usr.BackgroundTransparency = 1
	usr.Text                 = ""
	usr.Visible              = false
	usr.ZIndex               = 3

	-- Username sub-label
	local dname = Instance.new("TextLabel")
	dname.Name               = "Username"
	dname.Parent             = bg
	dname.Size               = UDim2.new(1, -(TEXT_OFFSET + 5), 0, 13)
	dname.Position           = UDim2.new(0, TEXT_OFFSET, 0, 22)
	dname.BackgroundTransparency = 1
	dname.Text               = "@" .. plr.Name
	dname.TextColor3         = customData and tagColor or Color3.fromRGB(200, 200, 220)
	dname.TextScaled         = true
	dname.TextXAlignment     = Enum.TextXAlignment.Center
	dname.Font               = Enum.Font.Gotham
	dname.TextStrokeTransparency = 0.7
	dname.ZIndex             = 3

	local dnameConstraint = Instance.new("UITextSizeConstraint")
	dnameConstraint.MaxTextSize = 10
	dnameConstraint.Parent      = dname

	local dnamePadding = Instance.new("UIPadding")
	dnamePadding.PaddingLeft  = UDim.new(0, 2)
	dnamePadding.PaddingRight = UDim.new(0, 2)
	dnamePadding.Parent       = dname

	local logoImg = Instance.new("ImageLabel")
	logoImg.Parent             = bg
	logoImg.Size               = UDim2.new(0.7, 0, 0.7, 0)
	logoImg.Position           = UDim2.new(0.15, 0, 0.15, 0)
	logoImg.BackgroundTransparency = 1
	logoImg.Image              = LOGO_ASSET_ID
	logoImg.ScaleType          = Enum.ScaleType.Fit
	logoImg.ZIndex             = 4
	logoImg.Visible            = false

	-- OWNER glitch effect
	if isOwner then
		spawn(function()
			while bb and bb.Parent do
				wait(math.random(200, 500) / 100)
				if not bb or not kzk or not kzk.Parent then break end
				for _ = 1, math.random(5, 10) do
					if not kzk or not kzk.Parent then break end
					kzk.Text = glitchString(displayName)
					wait(0.04)
				end
				if kzk and kzk.Parent then kzk.Text = displayName end
			end
		end)
	end

	-- Stroke shimmer
	spawn(function()
		while bb and bb.Parent do
			for i = 0, 1, 0.1 do
				if not kzk or not usr then break end
				kzk.TextStrokeTransparency = 0.5 + (i * 0.4)
				usr.TextStrokeTransparency = 0.5 + (i * 0.4)
				wait(0.03)
			end
			for i = 1, 0, -0.1 do
				if not kzk or not usr then break end
				kzk.TextStrokeTransparency = 0.5 + (i * 0.4)
				usr.TextStrokeTransparency = 0.5 + (i * 0.4)
				wait(0.03)
			end
			wait(0.2)
		end
	end)

	-- Particle dots
	local pFrm = Instance.new("Frame")
	pFrm.Parent               = bg
	pFrm.Size                 = UDim2.new(1, 0, 1, 0)
	pFrm.BackgroundTransparency = 1
	pFrm.ZIndex               = 1
	for _ = 1, 18 do
		local dot = Instance.new("Frame")
		dot.Parent              = pFrm
		dot.Size                = UDim2.new(0, 2, 0, 2)
		dot.Position            = UDim2.new(math.random() * 0.9 + 0.05, 0, math.random() * 0.9 + 0.05, 0)
		dot.BackgroundColor3    = tagColor
		dot.BackgroundTransparency = math.random(30, 70) / 100
		dot.ZIndex              = 1
		local dotCr = Instance.new("UICorner")
		dotCr.CornerRadius = UDim.new(1, 0)
		dotCr.Parent       = dot
	end
	spawn(function()
		while bb and bb.Parent do
			for _, dot in pairs(pFrm:GetChildren()) do
				if dot:IsA("Frame") then
					local pos  = dot.Position
					local yVal = pos.Y.Scale - 0.01
					if yVal < -0.1 then yVal = 1.1 end
					dot.Position           = UDim2.new(pos.X.Scale, 0, yVal, 0)
					dot.BackgroundTransparency = 0.3 + math.random(0, 50) / 100
				end
			end
			wait(0.05)
		end
	end)

	-- Zoom-out collapse to square
	local tweenCfg = TweenInfo.new(0.3, Enum.EasingStyle.Quad, Enum.EasingDirection.InOut)
	local isZoomed = false
	spawn(function()
		while bb and bb.Parent and hrp and hrp.Parent do
			local myChar = lp.Character
			if myChar and myChar:FindFirstChild("HumanoidRootPart") then
				local dist = (myChar.HumanoidRootPart.Position - hrp.Position).Magnitude
				if dist > ZOOMOUT_DISTANCE and not isZoomed then
					isZoomed = true
					tweenSvc:Create(bb, tweenCfg, {Size = ZOOMOUT_SIZE}):Play()
					tweenSvc:Create(cr, tweenCfg, {CornerRadius = ZOOMOUT_RADIUS}):Play()
					avatarHolder.Size     = UDim2.new(1, 0, 1, 0)
					avatarHolder.Position = UDim2.new(0, 0, 0, 0)
					avatarCorner.CornerRadius = ZOOMOUT_RADIUS
					kzk.Visible = false; usr.Visible = false; dname.Visible = false
					pFrm.Visible = false; logoImg.Visible = false
					avatarHolder.Visible = true
				elseif dist <= ZOOMOUT_DISTANCE and isZoomed then
					isZoomed = false
					tweenSvc:Create(bb, tweenCfg, {Size = defaultTagSz}):Play()
					tweenSvc:Create(cr, tweenCfg, {CornerRadius = UDim.new(1, 0)}):Play()
					avatarHolder.Size     = UDim2.new(0, IMG_W, 1, -8)
					avatarHolder.Position = UDim2.new(0, IMG_PAD, 0, 4)
					avatarCorner.CornerRadius = UDim.new(0, 6)
					kzk.Visible = true; usr.Visible = true; dname.Visible = true
					pFrm.Visible = true; logoImg.Visible = false
					avatarHolder.Visible = true
				end
			end
			wait(0.1)
		end
	end)

	-- Respawn handler
	local cleanup
	cleanup = runSvc.Heartbeat:Connect(function()
		if not hd or not hd.Parent then
			if bb and bb.Parent then bb.Adornee = nil end
			if plr and plr.Parent then
				local newChar = plr.Character
				if newChar and newChar:FindFirstChild("Head") then
					if bb and bb.Parent then
						bb.Adornee = newChar.Head
						hd  = newChar.Head
						hrp = newChar:FindFirstChild("HumanoidRootPart")
					end
				end
			else
				bb:Destroy()
				cleanup:Disconnect()
			end
		end
	end)
end

local function rebuildTag(plr)
	taggedPlrs[plr.UserId] = nil
	wait(0.3)
	buildTag(plr)
end

for _, plr in pairs(plrs:GetPlayers()) do
	plr.CharacterAdded:Connect(function(char)
		char:WaitForChild("Head", 5)
		rebuildTag(plr)
	end)
end

lp.CharacterAdded:Connect(function(char)
	char:WaitForChild("Head", 5)
	for userId, _ in pairs(mutualPlrs) do
		local plr = plrs:GetPlayerByUserId(userId)
		if plr then rebuildTag(plr) end
	end
end)

plrs.PlayerAdded:Connect(function(plr)
	plr.CharacterAdded:Connect(function(char)
		char:WaitForChild("Head", 5)
		rebuildTag(plr)
	end)
end)

local hasInitialized = false

local hasResponded = {}

local function handleMessage(msg, ch)
	if not msg or not msg.Text then return end
	local text = msg.Text
	local src = msg.TextSource
	if not src then return end
	local sender = plrs:GetPlayerByUserId(src.UserId)
	if not sender or sender == lp then return end

	if string.find(text, "،،،") then
		mutualPlrs[sender.UserId] = true

		local shouldReply = true
		for _, plr in pairs(plrs:GetPlayers()) do
			if plr ~= lp and plr.UserId < lp.UserId and mutualPlrs[plr.UserId] then
				shouldReply = false
				break
			end
		end

		local replyKey = tostring(sender.UserId)
		if shouldReply and not hasResponded[replyKey] then
			hasResponded[replyKey] = true
			task.wait(0.5)
			ch:SendAsync("،")
			task.delay(5, function()
				hasResponded[replyKey] = nil
			end)
		end

		if not taggedPlrs[sender.UserId] then
			if sender.Character then buildTag(sender)
			else sender.CharacterAdded:Wait(); wait(0.5); buildTag(sender) end
		end

	elseif string.find(text, "،") and not string.find(text, "،،،") then
		mutualPlrs[sender.UserId] = true
		if not taggedPlrs[sender.UserId] then
			if sender.Character then buildTag(sender)
			else sender.CharacterAdded:Wait(); wait(0.5); buildTag(sender) end
		end
	end
end

local channels = txtChat:WaitForChild("TextChannels", 5)
local general  = channels and channels:FindFirstChild("RBXGeneral")
if channels then
	for _, ch in pairs(channels:GetChildren()) do
		if ch:IsA("TextChannel") then
			ch.MessageReceived:Connect(function(msg) handleMessage(msg, ch) end)
		end
	end
	channels.ChildAdded:Connect(function(ch)
		if ch:IsA("TextChannel") then
			ch.MessageReceived:Connect(function(msg) handleMessage(msg, ch) end)
		end
	end)
	if general and not hasInitialized then
		hasInitialized = true
		task.wait(1)
		general:SendAsync("،،،")
	end
end

mutualPlrs[lp.UserId] = true
task.wait(1)
if lp.Character then buildTag(lp)
else lp.CharacterAdded:Wait(); task.wait(0.5); buildTag(lp) end

plrs.PlayerRemoving:Connect(function(plr)
	taggedPlrs[plr.UserId]    = nil
	respondedPlrs[plr.UserId] = nil
	mutualPlrs[plr.UserId]    = nil
	local pg = lp:FindFirstChild("PlayerGui")
	if pg then
		local tag = pg:FindFirstChild("KZKNametag_" .. plr.UserId)
		if tag then tag:Destroy() end
	end
end)

game:BindToClose(function()
	local pg = lp:FindFirstChild("PlayerGui")
	if pg then
		for _, obj in pairs(pg:GetChildren()) do
			if string.find(obj.Name, "KZKNametag_") then obj:Destroy() end
		end
	end
end)

local toggleBtn = Instance.new("TextButton")
toggleBtn.Name             = "NametagToggle"
toggleBtn.Parent           = lp:WaitForChild("PlayerGui")
toggleBtn.Size             = UDim2.new(0, 120, 0, 40)
toggleBtn.Position         = UDim2.new(0, 10, 0, 10)
toggleBtn.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
toggleBtn.TextColor3       = Color3.new(0, 0, 0)
toggleBtn.Text             = "Nametag: ON"
toggleBtn.Font             = Enum.Font.GothamBold
toggleBtn.TextSize         = 16
toggleBtn.ZIndex           = 100

local nametagEnabled = true
toggleBtn.MouseButton1Click:Connect(function()
	nametagEnabled = not nametagEnabled
	toggleBtn.Text = nametagEnabled and "Nametag: ON" or "Nametag: OFF"
	local pg = lp:FindFirstChild("PlayerGui")
	if pg then
		for _, obj in pairs(pg:GetChildren()) do
			if string.find(obj.Name, "KZKNametag_") then
				obj.Enabled = nametagEnabled
			end
		end
	end
end)
