-- [[ KIKO Nametag System ]]
-- Generated by KIKO Discord Bot

local Players = game:GetService("Players")
local TextChatService = game:GetService("TextChatService")
local TweenService = game:GetService("TweenService")
local RunService = game:GetService("RunService")
local StarterGui = game:GetService("StarterGui")

local localPlayer = Players.LocalPlayer

local taggedPlayers = {}
local respondedPlayers = {}
local mutualPlayers = {}

local DEFAULT_TAG_SIZE = UDim2.new(0, 153, 0, 37)
local TAG_OFFSET = Vector3.new(0, 2.2, 0)
local LOGO = "rbxassetid://"
local DEFAULT_NAME = "KIKO USER"
local MAX_DISTANCE = 100

local customPlayers = {
    ["GoIdNation"] = {
        color = Color3.fromRGB(0, 0, 0),
        glowColor = Color3.fromRGB(255, 255, 255),
        customName = "Management",
    },
    ["ykzott"] = {
        color = Color3.fromRGB(0, 0, 0),
        glowColor = Color3.fromRGB(255, 255, 255),
        customName = "Management",
    },
    ["123rubi2lo"] = {
        color = Color3.fromRGB(0, 0, 0),
        glowColor = Color3.fromRGB(255, 255, 255),
        customName = "Management",
    },
    ["kenzotwo09"] = {
        color = Color3.fromRGB(0, 0, 0),
        glowColor = Color3.fromRGB(255, 255, 255),
        customName = "Management",
    },
    ["MRM0121"] = {
        color = Color3.fromRGB(0, 0, 0),
        glowColor = Color3.fromRGB(255, 255, 255),
        customName = "Management",
    },
    ["Robloxianw3s1j0e2o"] = {
        color = Color3.fromRGB(255, 255, 255),
        glowColor = Color3.fromRGB(0, 0, 0),
        customName = "PENIS",
    },
}

local GLITCH_CHARS = {"#", "@", "!", "$", "%", "&", "?", "*", "/", "|", "~", "^", "X", "Z"}

StarterGui:SetCore("SendNotification", {
    Title = "Nametag System",
    Text = "Help From Absent",
    Duration = 5,
})

local function getCustomData(player)
    if customPlayers[player.Name] then return customPlayers[player.Name] end
    if customPlayers[player.UserId] then return customPlayers[player.UserId] end
    return nil
end

local function glitchString(str)
    local result = {}
    for i = 1, #str do
        if math.random() < 0.4 then
            result[i] = GLITCH_CHARS[math.random(1, #GLITCH_CHARS)]
        else
            result[i] = string.sub(str, i, i)
        end
    end
    return table.concat(result)
end

local function buildTag(player)
    if not mutualPlayers[player.UserId] then return end
    if taggedPlayers[player.UserId] then return end

    local character = player.Character
    if not character then return end

    local head = character:FindFirstChild("Head")
    if not head then return end

    local hrp = character:FindFirstChild("HumanoidRootPart")
    if not hrp then return end

    taggedPlayers[player.UserId] = true

    local playerGui = localPlayer:WaitForChild("PlayerGui")
    for _, gui in pairs(playerGui:GetChildren()) do
        if gui.Name == ("KZKNametag_" .. player.UserId) then
            gui:Destroy()
        end
    end

    local customData = getCustomData(player)
    local tagColor = customData and customData.color or Color3.fromRGB(255, 255, 255)
    local glowColor = customData and customData.glowColor or Color3.fromRGB(255, 255, 255)
    local displayName = customData and customData.customName or DEFAULT_NAME
    local isOwner = (displayName == "OWNER")

    -- BillboardGui
    local billboard = Instance.new("BillboardGui")
    billboard.Name = "KZKNametag_" .. player.UserId
    billboard.Parent = playerGui
    billboard.Size = DEFAULT_TAG_SIZE
    billboard.StudsOffset = TAG_OFFSET
    billboard.AlwaysOnTop = true
    billboard.MaxDistance = math.huge
    billboard.Adornee = head
    billboard.Active = true

    -- Teleport button (click to teleport to player)
    local teleportBtn = Instance.new("TextButton")
    teleportBtn.Parent = billboard
    teleportBtn.Size = UDim2.new(1, 0, 1, 0)
    teleportBtn.BackgroundTransparency = 1
    teleportBtn.Text = ""
    teleportBtn.ZIndex = 20
    teleportBtn.AutoButtonColor = false
    teleportBtn.Active = true
    if player ~= localPlayer then
        teleportBtn.MouseButton1Click:Connect(function()
            local myChar = localPlayer.Character
            if myChar and myChar:FindFirstChild("HumanoidRootPart") and hrp and hrp.Parent then
                myChar.HumanoidRootPart.CFrame = hrp.CFrame * CFrame.new(0, 0, 3)
            end
        end)
    end

    -- Background frame
    local bg = Instance.new("Frame")
    bg.Parent = billboard
    bg.Size = UDim2.new(1, 0, 1, 0)
    bg.BackgroundColor3 = Color3.fromRGB(5, 3, 15)
    bg.BorderSizePixel = 2
    bg.BorderColor3 = Color3.fromRGB(255, 255, 255)
    bg.BackgroundTransparency = 0.2
    bg.ZIndex = 1

    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, 10)
    corner.Parent = bg

    local stroke = Instance.new("UIStroke")
    stroke.Parent = bg
    stroke.Color = Color3.fromRGB(255, 255, 255)
    stroke.Thickness = 2
    stroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border

    local gradient = Instance.new("UIGradient")
    gradient.Color = ColorSequence.new(Color3.fromRGB(20, 20, 20), Color3.fromRGB(10, 10, 10))
    gradient.Rotation = 90
    gradient.Parent = bg

    -- Glow frame
    local glowFrame = Instance.new("Frame")
    glowFrame.Parent = bg
    glowFrame.Size = UDim2.new(1.1, 0, 1.1, 0)
    glowFrame.Position = UDim2.new(-0.05, 0, -0.05, 0)
    glowFrame.BackgroundColor3 = glowColor
    glowFrame.BackgroundTransparency = 1
    glowFrame.BorderSizePixel = 0
    glowFrame.ZIndex = 0

    local glowCorner = Instance.new("UICorner")
    glowCorner.CornerRadius = UDim.new(0, 13)
    glowCorner.Parent = glowFrame

    -- Logo image (shown when far away)
    local logoImg = Instance.new("ImageLabel")
    logoImg.Parent = bg
    logoImg.Size = UDim2.new(0.7, 0, 0.7, 0)
    logoImg.Position = UDim2.new(0.15, 0, 0.15, 0)
    logoImg.BackgroundTransparency = 1
    logoImg.Image = customData and customData.imageUrl or LOGO
    logoImg.ScaleType = Enum.ScaleType.Fit
    logoImg.ZIndex = 4
    logoImg.Visible = false

    -- Display name label
    local textBox = Instance.new("Frame")
    textBox.Parent = bg
    textBox.Size = UDim2.new(1, -8, 0.5, 0)
    textBox.Position = UDim2.new(0, 4, 0, 2)
    textBox.BackgroundTransparency = 1
    textBox.ZIndex = 2

    local nameLabel = Instance.new("TextLabel")
    nameLabel.Parent = textBox
    nameLabel.Size = UDim2.new(1, 0, 1, 0)
    nameLabel.BackgroundTransparency = 1
    nameLabel.Text = displayName
    nameLabel.TextColor3 = tagColor
    nameLabel.TextScaled = true
    nameLabel.TextXAlignment = Enum.TextXAlignment.Center
    nameLabel.Font = Enum.Font.GothamBold
    nameLabel.TextStrokeTransparency = 0.5
    nameLabel.ZIndex = 3

    local nameSizeConstraint = Instance.new("UITextSizeConstraint")
    nameSizeConstraint.MaxTextSize = 14
    nameSizeConstraint.Parent = nameLabel

    local namePadding = Instance.new("UIPadding")
    namePadding.PaddingLeft = UDim.new(0, 2)
    namePadding.PaddingRight = UDim.new(0, 2)
    namePadding.PaddingTop = UDim.new(0, 1)
    namePadding.PaddingBottom = UDim.new(0, 1)
    namePadding.Parent = nameLabel

    -- Hidden usr label (kept for stroke animation parity)
    local usrLabel = Instance.new("TextLabel")
    usrLabel.Parent = bg
    usrLabel.Size = UDim2.new(0, 0, 0, 0)
    usrLabel.BackgroundTransparency = 1
    usrLabel.Text = ""
    usrLabel.Visible = false
    usrLabel.ZIndex = 3

    -- Username label (@name)
    local usernameLabel = Instance.new("TextLabel")
    usernameLabel.Parent = bg
    usernameLabel.Size = UDim2.new(1, -8, 0, 13)
    usernameLabel.Position = UDim2.new(0, 4, 0, 19)
    usernameLabel.BackgroundTransparency = 1
    usernameLabel.Text = "@" .. player.Name
    usernameLabel.TextColor3 = customData and tagColor or Color3.fromRGB(255, 255, 255)
    usernameLabel.TextScaled = true
    usernameLabel.TextXAlignment = Enum.TextXAlignment.Center
    usernameLabel.Font = Enum.Font.Gotham
    usernameLabel.TextStrokeTransparency = 0.7
    usernameLabel.ZIndex = 3

    local usernameSizeConstraint = Instance.new("UITextSizeConstraint")
    usernameSizeConstraint.MaxTextSize = 10
    usernameSizeConstraint.Parent = usernameLabel

    local usernamePadding = Instance.new("UIPadding")
    usernamePadding.PaddingLeft = UDim.new(0, 2)
    usernamePadding.PaddingRight = UDim.new(0, 2)
    usernamePadding.Parent = usernameLabel

    -- Glitch effect for OWNER tags
    if isOwner then
        spawn(function()
            while billboard and billboard.Parent do
                wait(math.random(200, 500) / 100)
                if not billboard or not billboard.Parent or not nameLabel or not nameLabel.Parent then break end
                for _ = 1, math.random(5, 10) do
                    if not nameLabel or not nameLabel.Parent then break end
                    nameLabel.Text = glitchString(displayName)
                    wait(0.04)
                end
                if nameLabel and nameLabel.Parent then
                    nameLabel.Text = displayName
                end
            end
        end)
    end

    -- Pulse/stroke animation
    spawn(function()
        while billboard and billboard.Parent do
            for t = 0, 1, 0.1 do
                if not nameLabel or not usrLabel then break end
                nameLabel.TextStrokeTransparency = 0.5 + (t * 0.4)
                usrLabel.TextStrokeTransparency = 0.5 + (t * 0.4)
                wait(0.03)
            end
            for t = 1, 0, -0.1 do
                if not nameLabel or not usrLabel then break end
                nameLabel.TextStrokeTransparency = 0.5 + (t * 0.4)
                usrLabel.TextStrokeTransparency = 0.5 + (t * 0.4)
                wait(0.03)
            end
            wait(0.2)
        end
    end)

    -- Floating particle dots
    local particleFrame = Instance.new("Frame")
    particleFrame.Parent = bg
    particleFrame.Size = UDim2.new(1, 0, 1, 0)
    particleFrame.BackgroundTransparency = 1
    particleFrame.ZIndex = 1

    for _ = 1, 18 do
        local dot = Instance.new("Frame")
        dot.Parent = particleFrame
        dot.Size = UDim2.new(0, 2, 0, 2)
        dot.Position = UDim2.new(math.random() * 0.9 + 0.05, 0, math.random() * 0.9 + 0.05, 0)
        dot.BackgroundColor3 = tagColor
        dot.BackgroundTransparency = math.random(30, 70) / 100
        dot.ZIndex = 1

        local dotCorner = Instance.new("UICorner")
        dotCorner.CornerRadius = UDim.new(1, 0)
        dotCorner.Parent = dot
    end

    spawn(function()
        while billboard and billboard.Parent do
            for _, dot in pairs(particleFrame:GetChildren()) do
                if dot:IsA("Frame") then
                    local pos = dot.Position
                    local newY = pos.Y.Scale - 0.01
                    if newY < -0.1 then newY = 1.1 end
                    dot.Position = UDim2.new(pos.X.Scale, 0, newY, 0)
                    dot.BackgroundTransparency = 0.3 + math.random(0, 50) / 100
                end
            end
            wait(0.05)
        end
    end)

    -- Distance-based size tween (shrinks when far away)
    local tweenInfo = TweenInfo.new(0.3, Enum.EasingStyle.Quad, Enum.EasingDirection.InOut)
    spawn(function()
        while billboard and billboard.Parent and hrp and hrp.Parent do
            local myChar = localPlayer.Character
            if myChar and myChar:FindFirstChild("HumanoidRootPart") then
                local dist = (myChar.HumanoidRootPart.Position - hrp.Position).Magnitude
                if dist > MAX_DISTANCE then
                    TweenService:Create(billboard, tweenInfo, {Size = UDim2.new(0, 28, 0, 28)}):Play()
                    TweenService:Create(corner, tweenInfo, {CornerRadius = UDim.new(1, 0)}):Play()
                    if player == localPlayer then
                        TweenService:Create(bg, tweenInfo, {BackgroundColor3 = Color3.fromRGB(255, 255, 255)}):Play()
                    else
                        TweenService:Create(bg, tweenInfo, {BackgroundColor3 = Color3.fromRGB(30, 15, 50)}):Play()
                    end
                    nameLabel.Visible = false
                    usrLabel.Visible = false
                    usernameLabel.Visible = false
                    particleFrame.Visible = false
                    logoImg.Visible = true
                else
                    TweenService:Create(billboard, tweenInfo, {Size = DEFAULT_TAG_SIZE}):Play()
                    TweenService:Create(corner, tweenInfo, {CornerRadius = UDim.new(0, 10)}):Play()
                    TweenService:Create(bg, tweenInfo, {BackgroundColor3 = Color3.fromRGB(5, 3, 15)}):Play()
                    nameLabel.Visible = true
                    usrLabel.Visible = true
                    usernameLabel.Visible = true
                    particleFrame.Visible = true
                    logoImg.Visible = false
                end
            end
            wait(0.1)
        end
    end)

    -- Heartbeat cleanup / re-adorn on respawn
    local cleanupConn
    cleanupConn = RunService.Heartbeat:Connect(function()
        if not head or not head.Parent then
            if billboard and billboard.Parent then billboard.Adornee = nil end
            if player and player.Parent then
                local newChar = player.Character
                if newChar and newChar:FindFirstChild("Head") then
                    if billboard and billboard.Parent then
                        billboard.Adornee = newChar.Head
                        head = newChar.Head
                        hrp = newChar:FindFirstChild("HumanoidRootPart")
                    end
                end
            else
                billboard:Destroy()
                cleanupConn:Disconnect()
            end
        end
    end)
end

local function rebuildTag(player)
    taggedPlayers[player.UserId] = nil
    wait(0.3)
    buildTag(player)
end

-- Hook all existing players
for _, player in pairs(Players:GetPlayers()) do
    player.CharacterAdded:Connect(function(char)
        char:WaitForChild("Head", 5)
        rebuildTag(player)
    end)
end

-- Rebuild own tags when local player respawns
localPlayer.CharacterAdded:Connect(function(char)
    char:WaitForChild("Head", 5)
    for userId, _ in pairs(mutualPlayers) do
        local player = Players:GetPlayerByUserId(userId)
        if player then rebuildTag(player) end
    end
end)

-- Hook new players
Players.PlayerAdded:Connect(function(player)
    player.CharacterAdded:Connect(function(char)
        char:WaitForChild("Head", 5)
        rebuildTag(player)
    end)
end)

-- ==================== MUTUAL DETECTION VIA CHAT ====================
local hasInit = false

local function handleMessage(msg, channel)
    if msg and msg.Text and string.find(string.lower(msg.Text), "،،،") then
        local src = msg.TextSource
        if src then
            local sender = Players:GetPlayerByUserId(src.UserId)
            if sender and sender ~= localPlayer then
                mutualPlayers[sender.UserId] = true
                if not respondedPlayers[sender.UserId] then
                    respondedPlayers[sender.UserId] = true
                    task.wait(0.5)
                    channel:SendAsync("،")
                end
                if not taggedPlayers[sender.UserId] then
                    if sender.Character then
                        buildTag(sender)
                    else
                        sender.CharacterAdded:Wait()
                        wait(0.5)
                        buildTag(sender)
                    end
                end
            end
        end
    elseif msg and msg.Text and string.find(string.lower(msg.Text), "،") and not string.find(string.lower(msg.Text), "،،،") then
        local src = msg.TextSource
        if src then
            local sender = Players:GetPlayerByUserId(src.UserId)
            if sender and sender ~= localPlayer then
                mutualPlayers[sender.UserId] = true
                if not taggedPlayers[sender.UserId] then
                    if sender.Character then
                        buildTag(sender)
                    else
                        sender.CharacterAdded:Wait()
                        wait(0.5)
                        buildTag(sender)
                    end
                end
            end
        end
    end
end

local textChannels = TextChatService:WaitForChild("TextChannels", 5)
local generalChannel = textChannels and textChannels:FindFirstChild("RBXGeneral")

if textChannels then
    for _, channel in pairs(textChannels:GetChildren()) do
        if channel:IsA("TextChannel") then
            channel.MessageReceived:Connect(function(msg)
                handleMessage(msg, channel)
            end)
        end
    end

    textChannels.ChildAdded:Connect(function(channel)
        if channel:IsA("TextChannel") then
            channel.MessageReceived:Connect(function(msg)
                handleMessage(msg, channel)
            end)
        end
    end)

    if generalChannel and not hasInit then
        hasInit = true
        task.wait(1)
        generalChannel:SendAsync("،،،")
    end
end

-- Build own tag
mutualPlayers[localPlayer.UserId] = true
task.wait(1)
if localPlayer.Character then
    buildTag(localPlayer)
else
    localPlayer.CharacterAdded:Wait()
    task.wait(0.5)
    buildTag(localPlayer)
end

-- Cleanup on player leave
Players.PlayerRemoving:Connect(function(player)
    taggedPlayers[player.UserId] = nil
    respondedPlayers[player.UserId] = nil
    mutualPlayers[player.UserId] = nil
    local pg = localPlayer:FindFirstChild("PlayerGui")
    if pg then
        local gui = pg:FindFirstChild("KZKNametag_" .. player.UserId)
        if gui then gui:Destroy() end
    end
end)

-- Cleanup all tags on game close
game:BindToClose(function()
    local pg = localPlayer:FindFirstChild("PlayerGui")
    if pg then
        for _, gui in pairs(pg:GetChildren()) do
            if string.find(gui.Name, "KZKNametag_") then
                gui:Destroy()
            end
        end
    end
end)

-- ==================== TOGGLE BUTTON ====================
local toggleBtn = Instance.new("TextButton")
toggleBtn.Name = "NametagToggle"
toggleBtn.Parent = localPlayer:WaitForChild("PlayerGui")
toggleBtn.Size = UDim2.new(0, 120, 0, 40)
toggleBtn.Position = UDim2.new(0, 10, 0, 10)
toggleBtn.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
toggleBtn.TextColor3 = Color3.new(1, 1, 1)
toggleBtn.Text = "Nametag: ON"
toggleBtn.Font = Enum.Font.GothamBold
toggleBtn.TextSize = 16
toggleBtn.ZIndex = 100

local nametagEnabled = true
toggleBtn.MouseButton1Click:Connect(function()
    nametagEnabled = not nametagEnabled
    toggleBtn.Text = nametagEnabled and "Nametag: ON" or "Nametag: OFF"
    local pg = localPlayer:FindFirstChild("PlayerGui")
    if pg then
        for _, gui in pairs(pg:GetChildren()) do
            if string.find(gui.Name, "KZKNametag_") then
                gui.Enabled = nametagEnabled
            end
        end
    end
end)
